//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 11:20:15 AM MSK 
//


package com.example.service2.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for getOrderedRoutesReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getOrderedRoutesReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderedRoutesDto" type="{https://github.com/sloning/Service-oriented-architecture}orderedRoutesDto"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderedRoutesDto"
})
@XmlRootElement(name = "getOrderedRoutesReq")
public class GetOrderedRoutesReq {

    @XmlElement(required = true)
    protected OrderedRoutesDto orderedRoutesDto;

    /**
     * Gets the value of the orderedRoutesDto property.
     * 
     * @return
     *     possible object is
     *     {@link OrderedRoutesDto }
     *     
     */
    public OrderedRoutesDto getOrderedRoutesDto() {
        return orderedRoutesDto;
    }

    /**
     * Sets the value of the orderedRoutesDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderedRoutesDto }
     *     
     */
    public void setOrderedRoutesDto(OrderedRoutesDto value) {
        this.orderedRoutesDto = value;
    }

}
