//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 11:20:15 AM MSK 
//


package com.example.service2.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lengthFilterDto" type="{https://github.com/sloning/Service-oriented-architecture}lengthFilterDto"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lengthFilterDto"
})
@XmlRootElement(name = "getRouteByLengthReq")
public class GetRouteByLengthReq {

    @XmlElement(required = true)
    protected LengthFilterDto lengthFilterDto;

    /**
     * Gets the value of the lengthFilterDto property.
     * 
     * @return
     *     possible object is
     *     {@link LengthFilterDto }
     *     
     */
    public LengthFilterDto getLengthFilterDto() {
        return lengthFilterDto;
    }

    /**
     * Sets the value of the lengthFilterDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthFilterDto }
     *     
     */
    public void setLengthFilterDto(LengthFilterDto value) {
        this.lengthFilterDto = value;
    }

}
