//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 11:20:15 AM MSK 
//


package com.example.service2.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for getRoutesReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getRoutesReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idFrom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="idTo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idFrom",
    "idTo",
    "page",
    "size",
    "sort"
})
@XmlRootElement(name = "getRoutesReq")
public class GetRoutesReq {

    protected int idFrom;
    protected int idTo;
    protected int page;
    protected int size;
    @XmlElement(required = true)
    protected String sort;

    /**
     * Gets the value of the idFrom property.
     * 
     */
    public int getIdFrom() {
        return idFrom;
    }

    /**
     * Sets the value of the idFrom property.
     * 
     */
    public void setIdFrom(int value) {
        this.idFrom = value;
    }

    /**
     * Gets the value of the idTo property.
     * 
     */
    public int getIdTo() {
        return idTo;
    }

    /**
     * Sets the value of the idTo property.
     * 
     */
    public void setIdTo(int value) {
        this.idTo = value;
    }

    /**
     * Gets the value of the page property.
     * 
     */
    public int getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     */
    public void setPage(int value) {
        this.page = value;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(int value) {
        this.size = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSort(String value) {
        this.sort = value;
    }

}
