//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 08:57:51 PM MSK 
//


package com.example.service2.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for lengthFilterDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lengthFilterDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idFrom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="idTo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="length" type="{https://github.com/sloning/Service-oriented-architecture}length"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lengthFilterDto", propOrder = {
    "idFrom",
    "idTo",
    "length"
})
public class LengthFilterDto {

    protected int idFrom;
    protected int idTo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Length length;

    /**
     * Gets the value of the idFrom property.
     * 
     */
    public int getIdFrom() {
        return idFrom;
    }

    /**
     * Sets the value of the idFrom property.
     * 
     */
    public void setIdFrom(int value) {
        this.idFrom = value;
    }

    /**
     * Gets the value of the idTo property.
     * 
     */
    public int getIdTo() {
        return idTo;
    }

    /**
     * Sets the value of the idTo property.
     * 
     */
    public void setIdTo(int value) {
        this.idTo = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Length }
     *     
     */
    public Length getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Length }
     *     
     */
    public void setLength(Length value) {
        this.length = value;
    }

}
