//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 11:20:15 AM MSK 
//


package com.example.service2.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.github_com.sloning.service_oriented_architecture package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.github_com.sloning.service_oriented_architecture
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRouteByLengthReq }
     * 
     */
    public GetRouteByLengthReq createGetRouteByLengthReq() {
        return new GetRouteByLengthReq();
    }

    /**
     * Create an instance of {@link LengthFilterDto }
     * 
     */
    public LengthFilterDto createLengthFilterDto() {
        return new LengthFilterDto();
    }

    /**
     * Create an instance of {@link GetRouteByLengthRes }
     * 
     */
    public GetRouteByLengthRes createGetRouteByLengthRes() {
        return new GetRouteByLengthRes();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link GetOrderedRoutesReq }
     * 
     */
    public GetOrderedRoutesReq createGetOrderedRoutesReq() {
        return new GetOrderedRoutesReq();
    }

    /**
     * Create an instance of {@link GetOrderedRoutesRes }
     * 
     */
    public GetOrderedRoutesRes createGetOrderedRoutesRes() {
        return new GetOrderedRoutesRes();
    }

    /**
     * Create an instance of {@link GetRoutesReq }
     * 
     */
    public GetRoutesReq createGetRoutesReq() {
        return new GetRoutesReq();
    }

    /**
     * Create an instance of {@link GetRoutesRes }
     * 
     */
    public GetRoutesRes createGetRoutesRes() {
        return new GetRoutesRes();
    }

    /**
     * Create an instance of {@link OrderedRoutesDto }
     * 
     */
    public OrderedRoutesDto createOrderedRoutesDto() {
        return new OrderedRoutesDto();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

}
