//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 11:20:15 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/sloning/Service-oriented-architecture", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.service2.model;
