server:
  port: 31000
  ssl:
    enabled: true
    key-store: classpath:soa.jks
    key-store-password: helios
    key-store-type: JKS
spring:
  datasource:
    url: ${db_soa_host}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect