spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    driver-class-name: org.postgresql.Driver
    username: s283990
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    root: info
